### ISSUE TITLE
App crashes frequently

### ISSUE THREAD

**Issue by davidnewcomb** [restcase/apibldr#5]
I'm been trying to use this app for the last 2 hours. I can't even create 2 parameter api without it crashing.
I got to the point where I was saving it every time I did something, but when it got to that stage, it was just freezing up all the time. I saved one of the exceptions but I'm not sure how helpful it is.

![image](https://user-images.githubusercontent.com/951359/114321078-d6c5c780-9b10-11eb-8374-5c5e3be96946.png)

I've had to abandon my attempt and go back to vi :(

**Comment by danielgel** [comment]
Hey @davidnewcomb 

It appears that the `name` field is missing from one of the parameters.

Can you please provide an example of the OpenAPI JSON that you are trying to modify?
Also, can you please add here the flow that you are doing to modify the OpenAPI JSON so that I could trace the issue?

Thanks

**Comment by davidnewcomb** [comment]
Another hour of crashes and I managed to create this un-compilable yaml file:

[apibldr.yaml.txt](https://github.com/restcase/apibldr/files/6299370/apibldr.yaml.txt)

1)
In the file `description: 'Update '` did used to be a big description that got truncated while I was using the app.

2)
```
20:35:15 ~/Development/git/my-client 531 (master) $ yarn openapi
yarn run v1.22.10
$ openapi-generator generate -i apibldr.yaml -g javascript -o src/generated2
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 3, Warning count: 0
Errors: 
	-attribute components.parameters.For path parameter user_id the required value should be true
	-attribute paths.'/rating/{person_id}/{user_id}'(get).requestBody.content is missing
	-attribute components.parameters.For path parameter person_id the required value should be true

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I could not get the app set the 'required' the values. Either I set it and it forgot, or it wasn't in the place where it needed to be set.

3) The app gets muddled up with references and schemas.

4) There red trash can on request body, which makes me think there is an error somewhere but no identification what it is.

5) The spec allows adding parameters at path level then at method level. This is not supported in your app, it looks like it is but when it comes to compile time it fails.

There's no source code in this project, so I can't fix anything. Upload the source code and you can have more of my time.
